### ISSUE TITLE
Where to get?

### ISSUE THREAD

**Issue by ryanbeaton** [formtapez/ZigUP#1]
Brilliant project!
Where to get hardware?
Will they be sold assembled?

**Comment by formtapez** [comment]
Hi.
I'm not selling the hardware but you can get bare PCBs from me if you want to build it yourself.
I've added a [Bill of materials](https://github.com/formtapez/ZigUP#bill-of-materials-bom) to the end of the README.md file where you can find sellers for every component and contact info to get bare PCBs.

**Comment by ryanbeaton** [comment]
Thanks
I’m not a that proficient at soldering so it’s not for me unfortunately.
If you do start selling them let me know.

**Comment by h4nc** [comment]
Hi,

very interessting product. It's like a Zigbee Allrounder. 

I have some soldering skills and I'm considering making some of these. 

I already offer ready2use zigbee2mqtt sticks. 

See https://community.home-assistant.io/t/buy-a-ready2use-zigbee2mqtt-stick-flashed-antenna-mod-and-printed-case/111743

@formtapez Would you be fine with me offering these? Currently I cannot tell how much time it would take me to make one of these, so maybe it would get to expensive for users anyway.

**Comment by formtapez** [comment]
@h4nc sure, sell them if you like. Let me know when you need PCBs :)
But maybe you should wait some time for a cost-reduced version mentioned in #3

**Comment by h4nc** [comment]
Thank you. A cheaper version would be great (or necessary to make it interessting for people). I will probably make some suggestions in that other issue.

**Comment by aryehassbian** [comment]
> Hi.
> I'm not selling the hardware but you can get bare PCBs from me if you want to build it yourself.
> I've added a [Bill of materials](https://github.com/formtapez/ZigUP#bill-of-materials-bom) to the end of the README.md file where you can find sellers for every component and contact info to get bare PCBs.

That looks interesting..
Do you have Gerber file for download?
Thanks

**Comment by formtapez** [comment]
> > Hi.
> > I'm not selling the hardware but you can get bare PCBs from me if you want to build it yourself.
> > I've added a [Bill of materials](https://github.com/formtapez/ZigUP#bill-of-materials-bom) to the end of the README.md file where you can find sellers for every component and contact info to get bare PCBs.
> 
> That looks interesting..
> Do you have Gerber file for download?
> Thanks

Yes, check out https://github.com/formtapez/ZigUP/tree/master/Layout/Gerber

**Comment by darekhome** [comment]
Hi - possible to buy somewhere the PCB with at least 'smd' parts assembled...?
