### ISSUE TITLE
failed: lqi,routingTable

### ISSUE THREAD

**Issue by DD-NDD** [formtapez/ZigUP#11]
![image](https://user-images.githubusercontent.com/31593177/65947715-195e0c80-e463-11e9-9ed2-77c107df54d0.png)
It not in router mode.

**Comment by formtapez** [comment]
Did you flashed the Router- or EndDevice-Firmware?

**Comment by ngodinhduy** [comment]
i flash the Router firmware

**Comment by ngodinhduy** [comment]
![image](https://user-images.githubusercontent.com/31593177/66012667-38f04600-e4f2-11e9-814f-36203d646563.png)
Debug log

**Comment by ngodinhduy** [comment]
![image](https://user-images.githubusercontent.com/31593177/66012858-fb3fed00-e4f2-11e9-9780-c20818a0d0a1.png)
![image](https://user-images.githubusercontent.com/31593177/66012905-36422080-e4f3-11e9-8727-0a79a3306131.png)
Defined Symbols
SECURE=1
HAL_KEY=FALSE
HAL_LED=FALSE
HAL_LCD=FALSE
HAL_UART=FALSE
TC_LINKKEY_JOIN
NV_INIT
NV_RESTORE
xHOLD_AUTO_START
ZTOOL_P1
MT_TASK
MT_APP_FUNC
MT_SYS_FUNC
MT_ZDO_FUNC
LCD_SUPPORTED=FALSE
MULTICAST_ENABLED=FALSE
ZCL_READ
ZCL_WRITE
ZCL_REPORT
xZCL_EZMODE
ZCL_BASIC
ZCL_IDENTIFY
ZCL_ON_OFF
ZCL_SCENES
ZCL_GROUPS
xZCL_LEVEL_CTRL
ZCL_DIAGNOSTIC
FEATURE_SYSTEM_STATS
ZCL_DOORLOCK

Are my steps correct?

**Comment by formtapez** [comment]
Reporting is not supported, so this is no error in picture 2.
Is it working normally, disregarding of the missing routing?

**Comment by ngodinhduy** [comment]
It cannot extend the operating distance, because the router mode is not enabled.
