### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by copystring** [formtapez/ZigUP#12]
Is there a way to reset the pairing and re-pair?
I assume I have to flash this again to re-pair.
Or is there another way?

**Comment by formtapez** [comment]
If you have connected a button to the "key" input, you can press it for 5 seconds to initiate re-pairing.
Also when you turn off you coordinator so ZigUp is loosing connection, it enters re-pairing mode.

**Comment by copystring** [comment]
OK. Hold the button seems to initiate re-pairing. The relay clicks off and on quickly. Assuming it worked it does not re-enter my network. I have changed the  channel of my network to 13 and changed the pan_id as well.
Does that matter?

**Comment by formtapez** [comment]
Depends on which firmware you flashed. The precompiled hex files from the Release-section is fixed to channel 25.

**Comment by copystring** [comment]
Right. Changed back to channel 11. It works now with the precompiled firmware. Why do you say it is channel 25? It is channel 11. Am I missing something here?

**Comment by formtapez** [comment]
With "precompiled firmware" i mean the hex-files from the "release" section here on github.
I compiled them with
`-DDEFAULT_CHANLIST=0x02000000  // 25 - 0x19`
in zstack\Tools\CC2530DB\f8wConfig.cfg

The default there is channel 11. Did you compiled it yourself?

**Comment by copystring** [comment]
Nope. I am using the precompiled version. Could not be bothered to install all the tools.
