### ISSUE TITLE
int main( void)    highlighted in green after compiling

### ISSUE THREAD

**Issue by InvertedMinor** [formtapez/ZigUP#14]
When I compile the latest .EWW projectfile, it does the job but in the ZMain.C file the int main( void) line is highlighted in green. In the Disassembly box under main the following line is highlighted green:

058841 74 EF MOV a,#0xEF

?????

**Comment by formtapez** [comment]
Maybe you started debugging instead of just "build".

**Comment by InvertedMinor** [comment]
tried it, did not help
![mov](https://user-images.githubusercontent.com/37710269/67662032-e5431200-f962-11e9-8544-d860b4759b25.png)

**Comment by formtapez** [comment]
Select "Rebuild all" from the "Projects" menu, instead of whatever you are pressing.
