### ISSUE TITLE
It is perfect

### ISSUE THREAD

**Issue by freenetwork** [formtapez/ZigUP#2]
You have a great project. However, I wanted to learn how to program the TI CC2530 myself. Tell me how did you study? Very heavy entry.

**Comment by freenetwork** [comment]
This relay Can it be attached to a conbee?

**Comment by formtapez** [comment]
For flashing you can use a "CC Debugger" device. Described here: https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html
Or you can use an Arduino or Raspberry Pi:
https://www.zigbee2mqtt.io/information/alternative_flashing_methods.html

I don't know the "Conbee" device, but it seems it was build to pair with custom devices. So i would assume it should work.
