### ISSUE TITLE
illuminance sensor

### ISSUE THREAD

**Issue by anshgh** [formtapez/ZigUP#4]
Hi
Can I make a light sensor (illumination) with a BH1750?

**Comment by formtapez** [comment]
The processor doesnt have a TWI interface, so its not possible.
But you can use an analog sensor like a photoresistor or solar-cell on the analog-input pin.

**Comment by anshgh** [comment]
Tanks. 
I need high resolution illuminance. Because my sensor Aqara Motion Sensor gives a maximum of 1000 Lx and in cloudy and sunny weather.
![image (6)](https://user-images.githubusercontent.com/8523569/61525834-e1c5f380-aa21-11e9-93e8-e1572b462484.png)
![image (5)](https://user-images.githubusercontent.com/8523569/61525836-e25e8a00-aa21-11e9-9495-0fc3cf018bb2.png)
Do you know the illuminance sensor with WTI support?

**Comment by anshgh** [comment]
Which pins of the CC2530 (P00-P22) correspond to the pins on your board (Sensor, S0, ADC, DIG, LED, KEY)?

**Comment by formtapez** [comment]
Just have a look in the [schematic](https://raw.githubusercontent.com/formtapez/ZigUP/master/Layout/Images/schematic.png).

**Comment by anshgh** [comment]
Tanks. 
Can I buy such a module on Aliexpress?
![image](https://user-images.githubusercontent.com/8523569/61642187-2a431280-aca9-11e9-967b-9c66f99e5a8b.png)

**Comment by anshgh** [comment]
or - https://ru.aliexpress.com/item/32982000600.html

**Comment by formtapez** [comment]
These are no illumination sensors. But if you want to measure rotation angle, you can use them.

**Comment by anshgh** [comment]
Yes. I know. This is a variable resistor to replace (not solder) the element X2-3 to ADC0. https://user-images.githubusercontent.com/8523569/61642187-2a431280-aca9-11e9-967b-9c66f99e5a8b.png

I want to use the TEMP6000 light sensor. He is 5 volt. But in your circuit to ADC0 you need 1.15 volts. Therefore, I want to use a variable resistor (links above) to connect the TEMP6000.

**Comment by formtapez** [comment]
I dont think that works. The current is too low to drive the ADC. You need an active component there.

**Comment by anshgh** [comment]
Why? It works for me on esp8266.

**Comment by anshgh** [comment]
Can you help turn on the deep sleep mode for the CC2530 for 2 minutes in your firmware?

**Comment by anshgh** [comment]
> The processor doesnt have a TWI interface, so its not possible.
> But you can use an analog sensor like a photoresistor or solar-cell on the analog-input pin.

https://e2e.ti.com/support/wireless-connectivity/zigbee-and-thread/f/158/p/824148/3049477#3049477

**Comment by anshgh** [comment]
> The processor doesnt have a TWI interface, so its not possible.
> But you can use an analog sensor like a photoresistor or solar-cell on the analog-input pin.

I want to use a TEMP6000 sensor.
How often will data from analog sensors be transmitted?
Can I change this time?

**Comment by formtapez** [comment]
You can change the reporting interval (default: 30s) here:
https://github.com/formtapez/ZigUP/blob/ec3112c4933cfd9b377bc32b3dd97cde0bd6086c/src/ZigUP/Source/zcl_zigup.c#L28

**Comment by anshgh** [comment]
What is **adc_volt":2.259**? I connected TEMP6000 3.3v.
 zigbee2mqtt:info 8/14/2019, 3:16:25 PM MQTT publish: topic 'zigbee2mqtt/0x00124b001d6663ed', payload '{"state":"OFF","cpu_temperature":24.48,"external_temperature":null,"external_humidity":null,"s0_counts":0,"adc_volt":2.259,"dig_input":1,"reason":"timer","linkquality":134}'

**Comment by formtapez** [comment]
that seems pretty correct for me.
you can measure up to 32 volt due to that resistor-divider at the input.

**Comment by anshgh** [comment]
What you need to enable sleep mode (PM2).
"**You can define POWER_SAVING in project predefined symbols to enable it. After you define POWER_SAVING, CC2530 will enter sleeping mode automatically when there’s nothing in osal task queue.**"
Enable a compile option, del an "x" at the left edge of the line or add POWER_SAVING.

![image](https://user-images.githubusercontent.com/8523569/63350639-76e04300-c366-11e9-8ce8-f74f2fcebe72.png)

Awakening interval can be configured in the file zcl_zigup.c :
`#define ZIGUP_REPORTING_INTERVAL 120000 (120sec)`

Other than report interval, polling rate would wake up device every second by default.
You can change polling rate by changing -DPOLL_RATE in f8wconfig.cfg.

**Comment by anshgh** [comment]
I also changed the code in zcl_zigup.c to turn off the voltage of the TEMP6000 sensor during sleep mode. 
I connected TEMP6000 to 3.3v = P1.6 and data = P0.0
added:
`    // update measurements
    LED(1);
    _delay_ms(1000);
    Measure_QuickStuff();
    Measure_Sensor();
    LED(0);`

![image](https://user-images.githubusercontent.com/8523569/65422085-27ca7980-de0e-11e9-9bb8-d9a4fa4c4e6a.png)

commented:
`    //LED(1);`
![image](https://user-images.githubusercontent.com/8523569/65422369-e8505d00-de0e-11e9-8ea2-bbd58b8d1680.png)
