### ISSUE TITLE
Improve detail on how to flash HEX files

### ISSUE THREAD

**Issue by daparix** [formtapez/ZigUP#7]
I just build/soldered my first unit, and running following issues:
- Not sure of the polarity of the 10-pin programming connector. I understood it should be with red wire (pin 1) on the far side of the RF board (close to the connector of KEY/LED/DIG).

- I had to file one corner of the connector of the CC debugger cable before I could make it fit. Is this normal?

- It would be nice if there is some guideline to flash units with a default HEX file (I found it in another repository, but would be good to have default hex files here so compiling is not needed).

- As a bonus, would be great to have a guide to flash them using Ubuntu (i.e with cctool). I have found some bits of info, but as the default Windows flashing does not work, I do not dare to try a Linux flash yet.

PD: Not really in the main request as this part is not generic, but I can not flash the hex and would need some help:
The CC debugger shows red led when I do not connect the ZigUP and SmartRF Studio detects it right. If I plug the CC debugger with ZigUP connected, led shows off (and USB does not detect the CC debugger). Do I need to power ZigUP as well to 220V or it maybe some problem with my soldering - I just took a snapshop if someone can confirm it is right?

![IMG_20190821_004248](https://user-images.githubusercontent.com/1459049/63422655-19520200-c40b-11e9-9bd9-a5717bcba4aa.jpg)

![IMG_20190821_004238](https://user-images.githubusercontent.com/1459049/63422734-430b2900-c40b-11e9-8405-a964ccf68cd8.jpg)

**Comment by daparix** [comment]
![IMG_20190821_120900](https://user-images.githubusercontent.com/1459049/63423488-b5303d80-c40c-11e9-8c82-2a9ed674246d.jpg)

**Comment by daparix** [comment]
None: Just realized the HEX files can be got from "Releases" tab, but I meant to have the HEX files as part of the source tree as well for those users that are not very expert with GitHub

**Comment by formtapez** [comment]
Hi, please do not connect 220 Volts in this state - It is way too dangerous.
Powering via CC-Debugger is totally okay for programming.

It seems you have a short somewhere between GND and +3V3, when your Debugger-LED went off when plugging in. Can you measure resistance between this two signales?

Your polarity of the connector is right, and yes, it is very tight to the connector nearby.

**Comment by daparix** [comment]
thanks for all the feedback! 

indeed I have a short between 3.3V and GND. I tried visually and resoldered a couple of components, but I have still not fixed it, so will need to allocate more time. will come back as I progress on this, maybe I try a second unit mount (step by step) to progress on this, as I guess will be quicker/easier than finding the wrong solder or component in my first unit.

great work done by you!

**Comment by daparix** [comment]
Sorry to have delayed so much, I have too many projects in queue!!.
Built a second unit checking carefully each component soldering as I mounted them and I got a working one. Resistance between 3.3V and GND is around 4.5Kohm.

This one properly connects via CC_Debugger and I got a nice green led light, so ready to be programmed.

Many thanks!
