### ISSUE TITLE
GB2530 - Different Module

### ISSUE THREAD

**Issue by YeisonCL** [formtapez/ZigUP#8]
Hi,

First of all, kudos for this project, it is really incredible!

I have a quick question.

Is it possible to use a different module for this project? I noticed you used E18-MS1-PCB module for this project. I have a GB2530 module: [GB2530 Module](http://www.gban.cn/en/product_show.asp?id=47)

This module includes the CC2530 + RFX2401, can I use this module instead of  E18-MS1-PCB?

Thanks!

**Comment by formtapez** [comment]
Hi,
this module does not fit on the board, the footprint and pinout is different and you would have to include the controlling of the integrated RF-amplifier into the software.
